@extends('cms/layout')

@section('content')
  
  @include('cms/titleButtons', array('type' => 'edit', 'object' => $homepageStory, 'routeName' => 'HomepageStory', 'name'=> 'Homepage Story'))
	  
	  {!! $message = Session::get('message') !!}
	  @if(isset($homepageStory))
		  @if($homepageStory->id)
			  {!! Form::model($homepageStory, array('route' => array('updateHomepageStory', $homepageStory->id), 'files' => 'true')) !!}
		  @else
			  {!! 
				  Form::model($homepageStory, array('route' => array('addNewHomepageStory'), 'files' => 'true')) !!}
			@endif	 
		    <div class="formRow">
			    {!! Form::label('featured', 'Featured:') !!}
			    {!! Form::checkbox('featured', $homepageStory->featured, isset($homepageStory->featured) ? true : false) !!}
		    </div> 

		    <div class="formRow">
			    {!! Form::label('title', 'Title:') !!}
			    {!! Form::text('title', null, array('required')) !!}
		    </div> 


			  <div class="formRow">
			    {!! Form::label('slug', 'Slug: (this is autogenerated from the title)'); !!}
			    {!! Form::text('slug', $homepageStory->slug, array('class' => 'slug', 'readonly' => true) ); !!}
			    <input class="overrideSlug" name="overrideSlugCheckbox" type="checkbox"><label class="overrideSlugLabel" for="overrideSlugCheckbox">Override slug</label>
		    </div>

		    <div class="formRow">
			    {!! Form::label('featured_image', 'Featured Image:') !!}
			    
			    <div class="featuredImageContainer ">
			    
				    @if($featured_image) 
						    <div class="selectedFeaturedImage">

							    <p>Current Image:</p>
							    <img src="{{ route('getentry', $featured_image->filename) }}"  />
			            <div class="caption">
			                <small>File Name: {{ $featured_image->original_filename }}</small>
			            </div>
			            <button class="removeFeaturedImage button delete" type="button">Remove Featured Image</button>
							    {!! Form::hidden('featured_image', $homepageStory->featured_image) !!}
						    	
						    </div>
	          @else
		          <div class="featuredImageContainer addFeaturedImage">
						    {!! Form::file('featured_image', array('required')) !!}
					    </div>
				    @endif
			  
				  </div>

		    </div>

		    <div class="formRow">
			    {!! Form::label('description', 'Description:') !!}
				  {!! Form::textarea('description', $homepageStory->description , ['class' => 'wysiwyg']) !!}
		    </div>
		    

		    <div class="formRow">
			    {!! Form::label('user_id', 'User Type:') !!}
			    {!! Form::select('user_id', $selectUserTypes , $homepageStory->user_id , array('required', 'class' => 'formSelect')); !!}
		    </div>

			  @include('cms/submitButtons', array('object' => $homepageStory, 'routeName' => 'HomepageStory', 'name'=> 'Homepage Story'))


		@else
			<section class="col-xs-9">
			  Could not find User. Please try again.
			</section>
		@endif
@stop