@extends('cms/layout')

@section('content')
  
  @include('cms/titleButtons', array('object' => $event, 'name'=> 'Event'))

	  @if($event)
		  @if($event->id)
		    {!! Form::model($event, array('route' => array('updateEvent', $event->id))) !!}
		  @else
			  {!! Form::model($event, array('route' => array('addNewEvent'))) !!}
		  @endif
	    <section class="col-xs-9">
	    	<div class="formRow">
			    {!! Form::label('title', 'Event Title:') !!}
			    {!! Form::text('title') !!}
			  </div>
			  
			  <div class="formRow">
			    {!! Form::label('slug', 'Slug: (this is autogenerated from the title)') !!}
			    {!! Form::text('slug', $event->slug, array('class' => 'slug', 'readonly' => true) ) !!}
			    <input class="overrideSlug" name="overrideSlugCheckbox" type="checkbox"><label class="overrideSlugLabel" for="overrideSlugCheckbox">Override slug</label>
		    </div>



		    <div class="formRow">
			    {!! Form::label('description', 'Event Description:') !!}

				  <section class="tabs">
					  <div class="tabRow">
					  	<div class="tab markdownTab active">
					  		Markdown
					  	</div>
					  	<div class="tab codeTab">
					  		HTML
					  	</div>
					  	<div class="tab previewTab">
					  		Preview
					  	</div>
					  	<div id="md" class="tab modalInfo icon-info-circle"></div>
					  </div>
					  <div class="tabContent markdownWindow">
						  <textarea id="source" rows="10"></textarea>
					  </div>
					  <div class="tabContent codeWindow">
					    {!! Form::textarea('description', $event->description, array('class' => 'html', 'contenteditable' => true)) !!}
				    </div>
				    <div class="tabContent previewWindow">
					    <div class="editable visual" contenteditable="true"></div>
				    </div>
				  </section>

				  <section class="modalOverlay">
				  	<section class="modalWindow markdownModal md">
				  	<button class="modalClose icon-close" type="button"></button>
						  <h2>Markdown Syntax</h2>
						  <p>*single asterisks* == <em>italics</em></p>
						  <p>**double asterisks** == <strong>Bold</strong></p>
					  </section>
				  </section>

		    </div>
			  
			  <div class="formRow">
			    {!! Form::label('start_date','Start Date:') !!}
			    {!! Form::input('date','start_date') !!}
		    </div>
			  
			  <div class="formRow">
			    {!! Form::label('end_date','End Date:') !!}
			    {!! Form::input('date','end_date') !!}
		    </div>
			  
			  <div class="formRow">
			    {!! Form::label('start_time','Start Time:') !!}
			    {!! Form::input('time','start_time') !!}
		    </div>
			  
			  <div class="formRow">
			    {!! Form::label('end_time','End Time:') !!}
			    {!! Form::input('time','end_time') !!}
		    </div>
			  
			  <div class="formRow">
			    {!! Form::label('contact_name', 'Contact Name:') !!}
			    {!! Form::text('contact_name') !!}
		    </div>
			  
			  <div class="formRow">
			    {!! Form::label('contact_email', 'E-Mail Address:') !!}
			    {!! Form::email('contact_email') !!}
		    </div>
			  
			  <div class="formRow">
			    {!! Form::label('contact_phone', 'Contact Phone:') !!}
			    {!! Form::text('contact_phone') !!}
		    </div>
			  
			  <div class="formRow">
			    {!! Form::label('contact_url', 'Contact URL:') !!}
			    {!! Form::url('contact_url') !!}
		    </div>
			  
			  <div class="formRow">
			    {!! Form::label('location_id', 'Location:') !!}
			    {!! Form::select('location_id', $locationArray) !!}
		    </div>

		     <div class="formRow">
			    {!! Form::label('is_published', 'Is Approved?') !!}
			    {!! Form::checkbox('is_approved') !!}
		    </div>

		    <div class="formRow">
			    {!! Form::label('is_published', 'Is this record published?') !!}
			    {!! Form::checkbox('is_published') !!}
		    </div>
			  
			  @include('cms/submitButtons', array('object' => $event, 'routeName' => 'Event', 'name'=> 'Event'))

	    </section>
	    
	    <section class="col-xs-3 categoryRail">
		    <div class="formRow">
			    {!! Form::label('category_id', 'Categories:') !!}
			    @foreach ($categories as $category)
				    <div class="categoryRow">
					    <?php $catRel = EventCategoriesRel::where('category_id', '=', $category->id)->where('event_id' ,'=', $event->id)->first();?>
					    @if(is_null($catRel))
						    {!! Form::checkbox('categories[]', $category->id, false, array('class' => 'formCheckbox')) !!} {!! $category->category_name !!} 
					    @else
						    {!! Form::checkbox('categories[]', $category->id, true, array('class' => 'formCheckbox')) !!} {!! $category->category_name !!} 
				    	@endif
				    </div>
				    <?php $catRel = null ?>
			    @endforeach
		    </div>
		  </section>
		  
		@else
			<section class="col-xs-9">
			  Could not find Event. Please try again.
			</section>
		@endif
@stop